### ISSUE TITLE
画像素材調達交渉

### ISSUE THREAD

**Issue by dsuz** [fujishimatakumi/DropChipGame#1]
デザイナーチームに画像素材使用許可をもらうよう交渉してください。

リポジトリが public でもよいかどうかを決めて置いてください。

private でなければダメと言われたら、その時にリポジトリを private に変更してください。

**Comment by fujishimatakumi** [comment]
画像の使用許可を得ることができました
またpublicでも良いと言われたのでリポジトリはpublicにします。
以上のことからこのissueをcloseします
